export const PERMISSIONS = {
  // Students
  STUDENTS_READ: "students.read",
  STUDENTS_CREATE: "students.create",
  STUDENTS_UPDATE: "students.update",
  STUDENTS_DELETE: "students.delete",

  // Faculty
  FACULTY_READ: "faculty.read",
  FACULTY_CREATE: "faculty.create",
  FACULTY_UPDATE: "faculty.update",
  FACULTY_DELETE: "faculty.delete",

  // Courses
  COURSES_READ: "courses.read",
  COURSES_CREATE: "courses.create",
  COURSES_UPDATE: "courses.update",
  COURSES_DELETE: "courses.delete",

  // Enrollments
  ENROLLMENTS_READ: "enrollments.read",
  ENROLLMENTS_CREATE: "enrollments.create",
  ENROLLMENTS_UPDATE: "enrollments.update",
  ENROLLMENTS_DELETE: "enrollments.delete",

  // Attendance
  ATTENDANCE_READ: "attendance.read",
  ATTENDANCE_CREATE: "attendance.create",
  ATTENDANCE_UPDATE: "attendance.update",
  ATTENDANCE_DELETE: "attendance.delete",

  // Assignments
  ASSIGNMENTS_READ: "assignments.read",
  ASSIGNMENTS_CREATE: "assignments.create",
  ASSIGNMENTS_UPDATE: "assignments.update",
  ASSIGNMENTS_DELETE: "assignments.delete",

  // Submissions
  SUBMISSIONS_READ: "submissions.read",
  SUBMISSIONS_UPDATE: "submissions.update", // e.g. Grading

  // Exams
  EXAMS_READ: "exams.read",
  EXAMS_CREATE: "exams.create",
  EXAMS_UPDATE: "exams.update",
  EXAMS_DELETE: "exams.delete",

  // Results
  RESULTS_READ: "results.read",
  RESULTS_CREATE: "results.create",
  RESULTS_UPDATE: "results.update",
  RESULTS_PUBLISH: "results.publish",

  // Timetable
  TIMETABLE_READ: "timetable.read",
  TIMETABLE_CREATE: "timetable.create",
  TIMETABLE_UPDATE: "timetable.update",
  TIMETABLE_DELETE: "timetable.delete",

  // System
  SYSTEM_READ: "system.read",
  SYSTEM_UPDATE: "system.update",

  // Announcements
  ANNOUNCEMENTS_READ: "announcements.read",
  ANNOUNCEMENTS_CREATE: "announcements.create",
  ANNOUNCEMENTS_UPDATE: "announcements.update",
  ANNOUNCEMENTS_DELETE: "announcements.delete",

  // Notifications
  NOTIFICATIONS_READ: "notifications.read",
  NOTIFICATIONS_CREATE: "notifications.create",

  // Reports
  REPORTS_READ: "reports.read",

  // Settings
  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",

  // Audit Logs
  AUDIT_LOGS_READ: "audit_logs.read",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  admin: [
    PERMISSIONS.STUDENTS_READ, PERMISSIONS.STUDENTS_CREATE, PERMISSIONS.STUDENTS_UPDATE, PERMISSIONS.STUDENTS_DELETE,
    PERMISSIONS.FACULTY_READ, PERMISSIONS.FACULTY_CREATE, PERMISSIONS.FACULTY_UPDATE, PERMISSIONS.FACULTY_DELETE,
    PERMISSIONS.COURSES_READ, PERMISSIONS.COURSES_CREATE, PERMISSIONS.COURSES_UPDATE, PERMISSIONS.COURSES_DELETE,
    PERMISSIONS.ENROLLMENTS_READ, PERMISSIONS.ENROLLMENTS_CREATE, PERMISSIONS.ENROLLMENTS_UPDATE, PERMISSIONS.ENROLLMENTS_DELETE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_UPDATE, PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.ASSIGNMENTS_READ, PERMISSIONS.ASSIGNMENTS_CREATE, PERMISSIONS.ASSIGNMENTS_UPDATE, PERMISSIONS.ASSIGNMENTS_DELETE,
    PERMISSIONS.SUBMISSIONS_READ, PERMISSIONS.SUBMISSIONS_UPDATE,
    PERMISSIONS.EXAMS_READ, PERMISSIONS.EXAMS_CREATE, PERMISSIONS.EXAMS_UPDATE, PERMISSIONS.EXAMS_DELETE,
    PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_CREATE, PERMISSIONS.RESULTS_UPDATE, PERMISSIONS.RESULTS_PUBLISH,
    PERMISSIONS.TIMETABLE_READ, PERMISSIONS.TIMETABLE_CREATE, PERMISSIONS.TIMETABLE_UPDATE, PERMISSIONS.TIMETABLE_DELETE,
    PERMISSIONS.ANNOUNCEMENTS_READ, PERMISSIONS.ANNOUNCEMENTS_CREATE, PERMISSIONS.ANNOUNCEMENTS_UPDATE, PERMISSIONS.ANNOUNCEMENTS_DELETE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_CREATE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.AUDIT_LOGS_READ,
  ],
  faculty: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.ENROLLMENTS_READ,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_CREATE, PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ASSIGNMENTS_READ, PERMISSIONS.ASSIGNMENTS_CREATE, PERMISSIONS.ASSIGNMENTS_UPDATE, PERMISSIONS.ASSIGNMENTS_DELETE,
    PERMISSIONS.SUBMISSIONS_READ, PERMISSIONS.SUBMISSIONS_UPDATE,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.RESULTS_READ, PERMISSIONS.RESULTS_CREATE, PERMISSIONS.RESULTS_UPDATE,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ANNOUNCEMENTS_READ, PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.NOTIFICATIONS_READ, PERMISSIONS.NOTIFICATIONS_CREATE,
  ],
  student: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.ENROLLMENTS_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ASSIGNMENTS_READ,
    PERMISSIONS.SUBMISSIONS_READ,
    PERMISSIONS.EXAMS_READ,
    PERMISSIONS.RESULTS_READ,
    PERMISSIONS.TIMETABLE_READ,
    PERMISSIONS.ANNOUNCEMENTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
  ]
};

/**
 * Helper function to check if a role has a specific permission
 */
export function hasPermission(role: string, permission: Permission): boolean {
  if (role === 'super_admin') return true;
  if (!ROLE_PERMISSIONS[role]) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}
